language: node_js

os: linux

node_js:
  - node

cache: yarn

addons:
  chrome: stable

before_script:
  - npm install -g chromedriver

script:
  - yarn eslint
  - yarn build
  - yarn phantomjs-test
  - yarn browser-test
